apiVersion: v1
kind: Pod
metadata:
  name: etcd-version-monitor
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: etcd-version-monitor
    image: harbor.ultra.com/k8s/etcd-version-monitor:0.1.2
    command:
    - /etcd-version-monitor
    - --logtostderr
